### PR TITLE
Added Redmine 4.1.1 compatibility

### PR DESCRIPTION
**Pull request by reshetov**

### CODE REVIEW

**Comment by robspearman** [comment]
So redmine_crm is used for tagging.  Will any existing tag data be migrated?

What environments have you tested on?

Any updates to the README to go with this?

Thanks!

**Comment by reshetov** [comment]
redmine_crm gem uses rcrm_acts_as_taggable plugin with some patches for new Redmine versions. All tags already existing in DB will be available after update.
I tested code in this PR with

**Comment by reshetov** [comment]
redmine_crm gem uses rcrm_acts_as_taggable plugin with some patches for new Redmine versions. All tags already existing in DB will be available after update.
Code was tested with ruby 2.5.0|2.6.0 + Redmine 4.1.1|master branch
I think that not need any changes for README file. I didn't added any new functionality, just implement compatibility for new Redmine versions

**Comment by helmerfud** [comment]
hello,
I am updating my old redmine 3.4.6 to the new 4.1.1.
 
I am testing this fork anf there is an HTTP/500 on «tag_cloud»
My information:
Debian 10 fresh install

```
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Filesystem                     
Redmine plugins:
  redmine_callout_macro          1.0.0
  redmine_dmsf                   2.4.2
  redmine_drawio                 0.9.3
  redmine_gitlab_hook            4.0.0
  redmine_knowledgebase          3.3.1
```
production log:
```
Started GET "/redmine/projects/knowledgebase/knowledgebase/articles" for 10.xxx.xxx.xxx at 2020-04-16 17:10:23 +0200
Processing by ArticlesController#index as HTML
  Parameters: {"project_id"=>"knowledgebase"}
  Current user: UUUUUUUU (id=III)
  Rendering plugins/redmine_knowledgebase/app/views/articles/index.html.erb within layouts/base
  Rendered plugins/redmine_knowledgebase/app/views/categories/_jump_box.html.erb (12.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/articles/_list.html.erb (35.0ms)
  Rendered plugins/redmine_knowledgebase/app/views/articles/_list.html.erb (32.9ms)
  Rendered plugins/redmine_knowledgebase/app/views/articles/_list.html.erb (50.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/articles/_index_original.html.erb (119.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.2ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.2ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (4.1ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (21.2ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (6.9ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.4ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.2ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.2ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (21.0ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (5.6ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (4.2ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.2ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.2ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.3ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.2ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.2ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.2ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree_row.html.erb (1.2ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tree.html.erb (79.0ms)
  Rendered plugins/redmine_knowledgebase/app/views/categories/_tags.html.erb (62.8ms)
  Rendered plugins/redmine_knowledgebase/app/views/articles/index.html.erb within layouts/base (276.7ms)
Completed 500 Internal Server Error in 667ms (ActiveRecord: 84.8ms)
  
ActionView::Template::Error (undefined method `tag_cloud' for #<#<Class:0x00007f096dc0b908>:0x00007f096d48bde0>
Did you mean?  tag_builder):
    22:       <hr class="taglist-divider">
    23:     <% end %>
    24: 
    25:   <% tag_cloud(@tags, ['tag-x-small', 'tag-small', 'tag-medium', 'tag-large', 'tag-x-large']) do |tag, css_class| %>
    26: 
    27:     <% if !critical_tag_hash.has_key?( tag.name.downcase ) %>
    28:       <% if @tag && @tag_hash.has_key?( tag.name.downcase ) %>
  
plugins/redmine_knowledgebase/app/views/categories/_tags.html.erb:25:in `_plugins_redmine_knowledgebase_app_views_categories__tags_html_erb___847480446230379811_69839235979660'
plugins/redmine_knowledgebase/app/views/articles/index.html.erb:37:in `block in _plugins_redmine_knowledgebase_app_views_articles_index_html_erb___2407003416003304411_69839236390700'
plugins/redmine_knowledgebase/app/views/articles/index.html.erb:32:in `_plugins_redmine_knowledgebase_app_views_articles_index_html_erb___2407003416003304411_69839236390700'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:72:in `call'
```

Thank you.

**Comment by dtamajon** [comment]
I have upgrade to Redmine 4.1.1 from Redmine 3.3.2 and the plugin whith compatibility changes is working for me.

**Comment by reshetov** [comment]
@helmerfud  Could please you check again? I added commit with fix for your error

**Comment by helmerfud** [comment]
Hello,
thank you for your reactivity.
I have tested your fix and it work very well.
I have tested:
* acticle
** creation
** modicifcation
** deletiion
- tags
-- creation
-- deletion
-- click on tag

Best regards

**Comment by robspearman** [comment]
Sorry for the delay.  Thank you, @reshetov!

**Pull request merged**
