### PR TITLE
Preview does not work correctly with images on articles

### LINKED ISSUE #405: Preview does not work correctly with images on articles
I know there are also multiple issues already created with attachments. 

Preview works when adding a new image, and looking for preview just after. But it doesn't work if the article is saved and edited again. Then the URL to images is loaded incorrectly.

This is specially a big issue, when e.g. the [redmine_wysiwyg_editor](https://github.com/taqueci/redmine_wysiwyg_editor/) is used.

However, after some hours of research and testing, I found a way to solve this, which will follow in a PR later.

### PR DESCRIPTION
**Pull request by lauer**
This fixes #405 but also following issues

#383
#388
#396
#389

Currently only tested on Redmine 4.1.7.stable

### CODE REVIEW

**Comment by lauer** [comment]
It does also work on Redmine 4.2.x
But it does not work in Redmine 5.x - but that should be solved in #401

**Comment by lauer** [comment]
It does also solve #351

**Comment by lauer** [comment]
Great thanks. I also found this fork, which has some nice improvements. 
https://github.com/drakosu/redmine_knowledgebase

e.g. confirm on delete, which is actually quite nice to have :)

But his branch can't be merged automatically :/

**Comment by alexbevi** [comment]
@lauer if you're interested in maintaining this plugin just shoot me an email ;)

**Pull request merged**
